### ISSUE TITLE
💻 Criação da tela de atividade

### ISSUE THREAD

**Issue by cahhortega** [raphaelalkamim/macroChallengeEvents#42]

**Comment by biaduque** [comment]
* Protótipo referência da tela
![Image](https://user-images.githubusercontent.com/53840501/192030936-67deb639-4e81-444a-be49-9b280527e617.png)

**Comment by biaduque** [comment]
* Protótipo referência da tela
![Image](https://user-images.githubusercontent.com/53840501/192030936-67deb639-4e81-444a-be49-9b280527e617.png)
